"""Añadir campo nombre a Usuario

Revision ID: 7711bd996c41
Revises: 158aa86a2dec
Create Date: 2025-10-15 22:03:21.571364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7711bd996c41'
down_revision = '158aa86a2dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
