"""Añadir campo fecha_registro a Usuario

Revision ID: 937eeb11e17b
Revises: 7711bd996c41
Create Date: 2025-10-15 22:38:35.081590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937eeb11e17b'
down_revision = '7711bd996c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
